name: Build and Test
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build_client:
    name: Build Client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "npm"

      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-client-${{ github.event.pull_request.head.sha }}

      - name: Cache Build
        uses: actions/cache@v3
        with:
          path: dist
          key: ${{ runner.os }}-build-client-${{ github.event.pull_request.head.sha }}

      - name: Install Dependencies
        run: npm ci

      - name: Lint and Build
        run: npm run build:client
        env:
          VITE_ENABLE_LOGIN: true
          VITE_ENABLE_SIGNUP: true
          VITE_PUBNUB_PUBLISH_KEY: ${{ secrets.VITE_PUBNUB_PUBLISH_KEY }}
          VITE_PUBNUB_SUBSCRIBE_KEY: ${{ secrets.VITE_PUBNUB_SUBSCRIBE_KEY }}

  build_server:
    name: Build Server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "npm"

      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            server/node_modules
          key: ${{ runner.os }}-node-server-${{ github.event.pull_request.head.sha }}

      - name: Cache Build
        uses: actions/cache@v3
        with:
          path: server/dist
          key: ${{ runner.os }}-build-server-${{ github.event.pull_request.head.sha }}

      - name: Install Dependencies
        run: |
          cd server
          npm ci

      - name: Lint and Build
        run: npm run build:server

  test:
    name: Tests
    needs: [build_client, build_server]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Load Client Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-client-${{ github.event.pull_request.head.sha }}

      - name: Load Server Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            server/node_modules
          key: ${{ runner.os }}-node-server-${{ github.event.pull_request.head.sha }}

      - name: Load Client Build
        uses: actions/cache@v3
        with:
          path: dist
          key: ${{ runner.os }}-build-client-${{ github.event.pull_request.head.sha }}

      - name: Load Server Build
        uses: actions/cache@v3
        with:
          path: server/dist
          key: ${{ runner.os }}-build-server-${{ github.event.pull_request.head.sha }}

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "npm"

      - name: Unit Tests
        run: npm test

  deploy:
    name: Deploy Preview
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Load Server Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            server/node_modules
          key: ${{ runner.os }}-node-server-${{ github.event.pull_request.head.sha }}

      - name: Load Client Build
        uses: actions/cache@v3
        with:
          path: dist
          key: ${{ runner.os }}-build-client-${{ github.event.pull_request.head.sha }}

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "npm"

      - name: Pull Vercel Environment Information
        run: |
          cd server
          ./node_modules/.bin/vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: |
          cd server
          npm run export-version
          ./node_modules/.bin/vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Preview
        run: |
          cd server
          ./node_modules/.bin/vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
